//Main Config file
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js";//for initialization
import { getAuth, GoogleAuthProvider } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js";//for authentication
import { getFirestore } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";//imports firstore service
import { getStorage } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-storage.js";//for enabling cloud storage such as uploading photos

const firebaseConfig = {//contains project credentials generated by firebase console 
  apiKey: "AIzaSyCH-Q-CNWEKN-_ei5KEsQUa7OS7A4JHf7w",
  authDomain: "comfytest-399e5.firebaseapp.com",
  projectId: "comfytest-399e5",
  storageBucket: "comfytest-399e5.appspot.com",
  messagingSenderId: "498883406535",
  appId: "1:498883406535:web:b32caf8f7bcd3218cd2ce2"
};

const app = initializeApp(firebaseConfig);//connects web application with firebase

export const auth = getAuth(app);//exporting is done so that other modules can use this instance
export const provider = new GoogleAuthProvider();
export const db = getFirestore(app);
export const storage = getStorage(app);
